
FIND_PATH(REALSENSE2_INCLUDE_DIR libREALSENSE HINTS "/usr/include/librealsense2")
FIND_LIBRARY(REALSENSE2_LIBRARY REALSENSE HINTS "/usr/lib/x86_64-linux-gnu")

find_package_handle_standard_args(REALSENSE2 DEFAULT_MSG REALSENSE2_LIBRARY REALSENSE2_INCLUDE_DIR)

mark_as_advanced(REALSENSE2_LIBRARY REALSENSE2_INCLUDE_DIR)

